### ISSUE TITLE
Hello, I have a small question about hover background color.

### ISSUE THREAD

**Issue by l3ony2k** [pengx17/logseq-laurel-theme#1]
Hello! I just found this great theme and I'm trying to make some color change (I personally prefer a dark & red color scheme). But I can't change the hover background color of page reference in the dark theme. 

![image](https://user-images.githubusercontent.com/58762081/116957142-b3cea380-acc9-11eb-9ac1-2b61387b8aa2.png)

I've change every color code relates to page reference and hover, but I still got this green-ish background color when I hover on a page reference.

It would be great if you can tell me where should I make some tweaks. Thanks a lot!

**Comment by l3ony2k** [comment]
I managed to solved it! I tried claiming `--ls-tertiary-background-color` and `--ls-secondary-background-color` to designated colors and it worked! I'll upload my own theme to GitHub. Thanks again for the great work!

![image](https://user-images.githubusercontent.com/58762081/116965855-6f4f0200-ace1-11eb-9ad6-086c428f5b31.png)

**Comment by pengx17** [comment]
> I managed to solved it! I tried claiming `--ls-tertiary-background-color` and `--ls-secondary-background-color` to designated colors and it worked! I'll upload my own theme to GitHub. Thanks again for the great work!
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/58762081/116965855-6f4f0200-ace1-11eb-9ad6-086c428f5b31.png)

Great!
