### ISSUE TITLE
markdown 格式下编辑代码块异常

### ISSUE THREAD

**Issue by Littlecowherd** [pengx17/logseq-laurel-theme#2]
版本： v1.4.5

输入\`\`\`时会出现问题，不能正常输入和渲染。直接复制完整代码时可以渲染，但\`\`\`只会显示一个`。

![image](https://user-images.githubusercontent.com/19882756/118431949-02d4f980-b70a-11eb-82a2-43534a7cc999.png)

**Comment by pengx17** [comment]
@Littlecowherd 这个问题应该是Logseq本身的问题，跟样式文件无关，你可以把custom.css清除再看看是否有这个问题。 
请问你的Logseq版本号是什么？0.20.0版本的code editor不是特别稳定，容易把源文件搞坏。
这个问题应该是Logseq本身的问题，跟样式文件无关，你可以把custom.css清除再看看是否有这个问题。

**Comment by Littlecowherd** [comment]
默认主题是可以正确处理的呀
![image](https://user-images.githubusercontent.com/19882756/118452312-9c130880-b728-11eb-9298-efce6ab96b94.png)
![image](https://user-images.githubusercontent.com/19882756/118452332-9fa68f80-b728-11eb-879f-70ea0e698849.png)

**Comment by pengx17** [comment]
样式文件不会对文件渲染的内容有侵入，请使用 canary 版本再试试吧，0.0.20 的代码编辑块的问题比较多。

**Comment by Littlecowherd** [comment]
试了下客户端好像和不能加载 custom.css 文件，不知道哪里有问题。

源主题也是正常的，github.com/PiotrSss/logseq-clean-themes/blob/main/custom.css
![image](https://user-images.githubusercontent.com/19882756/118482122-e30ff680-b746-11eb-9926-d2fcfbaf6750.png)
此外我还注意到，你的主题在渲染代码块时是没有展示语言类型的，源主题和默认主题都有。
抱歉，我不太熟悉前端，没办法提供更多信息了……

**Comment by Littlecowherd** [comment]
找到原因了，Noto Sans 不支持重音符
![image](https://user-images.githubusercontent.com/19882756/119317924-44861700-bcab-11eb-9cbe-7d6b803b7eb0.png)

修改第23行如下，可以解决该问题
--ct-font-family: "Noto Sans SC", sans-serif;

**Comment by pengx17** [comment]
已经去掉了 "Noto Sans" 字体
