### ISSUE TITLE
CDN link outdated

### ISSUE THREAD

**Issue by eric-hansen** [pengx17/logseq-laurel-theme#4]
Not sure if this is intentional or not, so just figured I'd file an issue here first but if a PR is desired I can make one.

In the README you have the `@import` line:

```
@import url('https://cdn.jsdelivr.net/gh/pengx17/logseq-laurel-theme@1.8.1/custom.css');
```

As of this writing the current release is 1.8.4.  Is there a reason to not just use `@master` instead of `@<version>` instead?

**Comment by pengx17** [comment]
This readme file is currently manually maintained and I forgot to update them accordingly when updating the styles.

I think normally users can use master version as you suggested, but it has some caching timeout which I am not sure how long will it is?

**Comment by eric-hansen** [comment]
> 
> 
> This readme file is currently manually maintained and I forgot to update them accordingly when updating the styles.
> 
> I think normally users can use master version as you suggested, but it has some caching timeout which I am not sure how long will it is?

I'm not aware of any caching but it is a CDN after all so it is possible, but even if so the overall benefit to me of not having to manually update a README for the sake of versioning outweighs the cost of time and potential forgetfulness.

If you feel there's more value in manually maintaining then I respect that.  I was mainly pitching this to make the friction of updates to a theme a little less.

**Comment by pengx17** [comment]
> If you feel there's more value in manually maintaining then I respect that. I was mainly pitching this to make the friction of updates to a theme a little less.

Thanks! I have a check on the caching header of jsDelivr on master branch and it seems cache TTL is 7d. I think it should be safe to indicate the users to use master version for convenience!
