### ISSUE TITLE
code block does not work with theme

### ISSUE THREAD

**Issue by fredguth** [pengx17/logseq-laurel-theme#6]
In the default theme, if I insert the following text:

\`\`\`clojure
  (println "Hello world!")
\`\`\`

it renders as a code block.
```clojure
  (println "Hello world!")
```
When I try to enter such code in laurel theme, it does not work.

**Comment by pengx17** [comment]
@fredguth this is an issue in Logseq, not caused by the theme. In logseq there is an issue when pasting codes into code block. Please exit edit mode and paste your code directly into the code editor directly instead.

**Comment by fredguth** [comment]
I am new to logseq, what do you mean by exit edit mode and paste in code editor directly?

**Comment by pengx17** [comment]
https://user-images.githubusercontent.com/584378/142096687-aee45380-d17f-429f-90af-fb74adb111aa.mp4

Like this

**Comment by fredguth** [comment]
I am not sure if we are talking about the same problem.   When I try using the quote, it appears as all quotes are in the same place. If I change the theme, I see that I pressed quote many times:
https://share.getcloudapp.com/bLudlqRQ

**Comment by pengx17** [comment]
Have you tried the same steps to reproduce for other themes? I think theme is not the root issue though.
