### ISSUE TITLE
Huge header (in logseq 0.5.8)

### ISSUE THREAD

**Issue by pihentagy** [pengx17/logseq-laurel-theme#7]
Wrong value for `--ct-header-height`, 

For me, the header is huge, the offending setting seems to be
```
 --ct-header-height: 50px;
```

However, the computed height of the selected element is 120px :open_mouth: 

![image](https://user-images.githubusercontent.com/29916/148560320-11142e5a-6869-42d1-ba52-3446716ab2f6.png)

**Comment by PixelTux** [comment]
Could you please confirm if this issue is still present in the latest Logsq release. Also, it would be helpful if you could share the setup and the steps to reproduce the issue.

**Comment by pihentagy** [comment]
Seems to work fine now.

**Comment by PixelTux** [comment]
Thanks for getting back to me so quickly! I really appreciate your help. I think we can close this issue now.
