### ISSUE TITLE
中间编辑区能不能放大点

### ISSUE THREAD

**Issue by jayus71** [pengx17/logseq-laurel-theme#8]
中间编辑区有点小了，配色我很喜欢，能不能在主题设置里放一个设置大小的选项呢？或者请指路代码的位置，十分感谢！

**Comment by pengx17** [comment]
在Logseq中可以通过快捷键 `t w` 将编辑区域增大

**Comment by jayus71** [comment]
好的好的 以前没注意这个快捷键
